# Generated by Django 5.1.6 on 2025-02-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=100)),
            ],
        ),
    ]
